service: lambda-boilerplate # NOTE: update this with your service name

plugins:
    - serverless-dotenv-plugin
    - serverless-scriptable-plugin
    - aws-amplify-serverless-plugin
    - serverless-s3-sync
    - serverless-webpack
    - serverless-dynamodb-local
    - serverless-offline
    - serverless-offline-sns
    - serverless-iam-roles-per-function

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-west-2'}
    profile: ${self:custom.profiles.${self:provider.stage}, 'default'}
    environment:
        API_PREFIX: ${self:custom.apiPrefix}
        # AWS_REGION: ${self:provider.region}
        ROOT_TOPIC_ARN: ${self:custom.rootTopicArn}
        RESOURCE_ROOT: ${self:custom.resourceRoot}
        DEV_DYNAMO_ENDPOINT: "http://localhost:4567"
        DEV_SNS_ENDPOINT: "http://localhost:4002"

# package:
    # individually: true

custom: ${file(config/serverless.custom.js):default}

functions:
    - hello:
        handler: src/lambda/hello.default
        events:
            - http:
                method: GET
                path: /${self:custom.apiPrefix}/hello
                cors: true

resources:
    - ${file(config/resources/static-files.yml)}
    - ${file(config/resources/static-proxy.yml)}
    - ${file(config/resources/cognito-auth.yml)}
    - ${file(config/resources/cloudfront.yml)}
