connect:
    handler: src/lambda/example/ws.connect
    events:
        - websocket:
            route: $connect
            routeResponseSelectionExpression: $default

disconnect:
    handler: src/lambda/example/ws.disconnect
    events:
        - websocket:
            route: $disconnect
            routeResponseSelectionExpression: $default

ws_default:
    handler: src/lambda/example/ws.ws_default
    events:
        - websocket:
            route: $default
            routeResponseSelectionExpression: $default

sendto:
    handler: src/lambda/example/ws.http
    events:
        -   http:
                method: ANY
                path: ${self:custom.apiPrefix}/example/ws
                cors: true
